// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintHub.Database;

#nullable disable

namespace PrintHub.Migrations
{
    [DbContext(typeof(PrintHubContext))]
    partial class PrintHubContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintHub.Database.Models.CostBreakdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Calculated_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Filament_Cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Labor_Cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Material_Cost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Power_Cost")
                        .HasColumnType("numeric");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Project_ID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total_Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Waste_Cost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CostBreakdowns");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Filament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Cost_Per_Kg")
                        .HasColumnType("numeric");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Density")
                        .HasColumnType("numeric");

                    b.Property<string>("Material_Type")
                        .HasColumnType("text");

                    b.Property<string>("Texture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("PrintHub.Database.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Change_Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Item_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Item_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost_Per_Unit")
                        .HasColumnType("numeric");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Initial_Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<decimal>("Total_Material")
                        .HasColumnType("numeric");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("PrintHub.Database.Models.PriceModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Effective_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Labor_Per_Hour")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Labor_Time")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Power_Usage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Profit_Margin")
                        .HasColumnType("numeric");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Project_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Version")
                        .HasColumnType("integer");

                    b.Property<decimal>("Waste_Modifier")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("PriceModifiers");
                });

            modelBuilder.Entity("PrintHub.Database.Models.PrintEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Project_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("PrintEvents");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Printer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Power_Per_Hour")
                        .HasColumnType("numeric");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Labor")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Print_Time")
                        .HasColumnType("numeric");

                    b.Property<int>("PrinterId")
                        .HasColumnType("integer");

                    b.Property<int>("Printer_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PrintHub.Database.Models.ProjectFilament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost_At_Time")
                        .HasColumnType("numeric");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Filament_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Project_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Usage_G")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Filament_ID");

                    b.HasIndex("Project_ID");

                    b.ToTable("ProjectFilaments");
                });

            modelBuilder.Entity("PrintHub.Database.Models.ProjectMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost_At_Time")
                        .HasColumnType("numeric");

                    b.Property<string>("Created_By")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Material_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Project_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated_On")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Usage")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Material_ID");

                    b.HasIndex("Project_ID");

                    b.ToTable("ProjectMaterials");
                });

            modelBuilder.Entity("PrintHub.Database.Models.CostBreakdown", b =>
                {
                    b.HasOne("PrintHub.Database.Models.Project", "Project")
                        .WithMany("CostBreakdowns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrintHub.Database.Models.PriceModifier", b =>
                {
                    b.HasOne("PrintHub.Database.Models.Project", "Project")
                        .WithMany("PriceModifiers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrintHub.Database.Models.PrintEvent", b =>
                {
                    b.HasOne("PrintHub.Database.Models.Project", "Project")
                        .WithMany("PrintEvents")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Project", b =>
                {
                    b.HasOne("PrintHub.Database.Models.Printer", "Printer")
                        .WithMany("Projects")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrintHub.Database.Models.ProjectFilament", b =>
                {
                    b.HasOne("PrintHub.Database.Models.Filament", "Filament")
                        .WithMany("ProjectFilaments")
                        .HasForeignKey("Filament_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrintHub.Database.Models.Project", "Project")
                        .WithMany("ProjectFilaments")
                        .HasForeignKey("Project_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrintHub.Database.Models.ProjectMaterial", b =>
                {
                    b.HasOne("PrintHub.Database.Models.Material", "Material")
                        .WithMany("ProjectMaterials")
                        .HasForeignKey("Material_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrintHub.Database.Models.Project", "Project")
                        .WithMany("ProjectMaterials")
                        .HasForeignKey("Project_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Filament", b =>
                {
                    b.Navigation("ProjectFilaments");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Material", b =>
                {
                    b.Navigation("ProjectMaterials");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Printer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("PrintHub.Database.Models.Project", b =>
                {
                    b.Navigation("CostBreakdowns");

                    b.Navigation("PriceModifiers");

                    b.Navigation("PrintEvents");

                    b.Navigation("ProjectFilaments");

                    b.Navigation("ProjectMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
